Repository ngocnguyenbk/myapp, pull requests merged in 2020-10, with the labels that each got.

#12 11012: Add gem rubocop, pry
  .rubocop.yml
  .rubocop_todo.yml
  Capfile
  Gemfile
  Gemfile.lock
  Rakefile
  app/mailers/application_mailer.rb
  config.ru
  config/boot.rb
  config/deploy.rb
  config/deploy/production.rb
  config/deploy/staging.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/initializers/assets.rb
  test/channels/application_cable/connection_test.rb
  test/test_helper.rb
Labels: Inreview, LGTM

#13 11013: Fix text
  app/views/home_pages/index.html.erb
  setup_rubydev.md
Labels: LGTM

#14 11014: Add gem slim
  Gemfile
  Gemfile.lock
  app/javascript/packs/application.js
  app/views/home_pages/index.html.erb
  app/views/home_pages/index.html.slim
  app/views/layouts/application.html.erb
  app/views/layouts/application.html.slim
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  package.json
  yarn.lock
Labels: LGTM

#15 11015: Add user
  Gemfile
  Gemfile.lock
  app/models/concerns/soft_deletable.rb
  app/models/user.rb
  db/migrate/20201006095052_create_users.rb
  db/schema.rb
Labels: LGTM

#18 11017: Build CI github
  .github/workflows/ruby.yml
  config/database.yml.ci
  config/database_example.yml
  db/schema.rb
Labels: LGTM

#16 11016: Login Function
  .env.sample
  .github/workflows/ruby.yml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/controllers/application_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/sessions_controller.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.slim
  app/views/devise/sessions/new.html.slim
  app/views/devise/shared/_links.html.slim
  app/views/home_pages/index.html.slim
  app/views/layouts/login.html.slim
  config/environment.rb
  config/environments/development.rb
  config/initializers/devise.rb
  config/initializers/simple_form.rb
  config/initializers/simple_form_bootstrap.rb
  config/locales/devise.en.yml
  config/locales/en.yml
  config/locales/model.en.yml
  config/locales/simple_form.en.yml
  config/routes.rb
  config/webpack/environment.js
  db/migrate/20201006144311_add_devise_to_users.rb
  db/schema.rb
  lib/templates/erb/scaffold/_form.html.erb
  package.json
  yarn.lock
Labels: Inreview

#22 11021: Create Readme
  README.md
Labels: LGTM

#23 11022: Add routes API
  config/initializers/routes_reloader.rb
  config/initializers/routing_draw.rb
  config/routes.rb
  config/routes/api.rb
Labels: LGTM

#21 11019: Add webpacker, users index
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/_custom_styles.scss
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/application.css.scss
  app/assets/stylesheets/pages/users.scss
  app/assets/stylesheets/styles.scss
  app/controllers/users_controller.rb
  app/javascript/api/axios.js
  app/javascript/api/users.js
  app/javascript/component_users/rowUser.vue
  app/javascript/component_users/tableUsers.vue
  app/javascript/components/paginator.vue
  app/javascript/packs/application.js
  app/javascript/store/index.js
  app/javascript/store/modules/user.js
  app/javascript/user.vue
  app/models/concerns/date_format.rb
  app/models/user.rb
  app/presenters/users_presenter.rb
  app/serializers/user_list_serializer.rb
  app/serializers/user_serializer.rb
  app/views/home_pages/index.html.slim
  app/views/layouts/application.html.slim
  app/views/users/index.html.slim
  config/initializers/kaminari_config.rb
  config/routes.rb
  config/webpack/environment.js
  config/webpack/loaders/vue.js
  config/webpacker.yml
  db/seeds.rb
  db/seeds/development.rb
  lib/tasks/default_data.rake
  package.json
  yarn.lock
Labels: LGTM

#24 11023_manh:fixMixinWarning
  app/assets/stylesheets/_variables.scss
  app/assets/stylesheets/styles.scss
  package.json
  yarn.lock
Labels: LGTM

#25 11020: Api for Floors
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/floors_controller.rb
  app/javascript/api/floors.js
  app/javascript/floor.vue
  app/javascript/packs/application.js
  app/javascript/store/index.js
  app/javascript/store/modules/floor.js
  app/models/floor.rb
  app/models/room.rb
  app/models/user.rb
  app/presenters/floors_presenter.rb
  app/serializers/floor_list_serializer.rb
  app/serializers/floor_serializer.rb
  app/serializers/room_serializer.rb
  app/views/floors/index.html.slim
  app/views/layouts/application.html.slim
  config/routes.rb
  db/migrate/20201016075920_create_floors.rb
  db/migrate/20201016080932_create_rooms.rb
  db/migrate/20201016081238_add_foreign_key_user_room.rb
  db/migrate/20201023014451_add_column_to_rooms.rb
  db/schema.rb
  db/seeds/development.rb
  lib/tasks/default_data.rake
Labels: LGTM

#26 11023: Add floors, rooms.
  app/assets/stylesheets/_custom_styles.scss
  app/assets/stylesheets/styles.scss
  app/javascript/component_floors/rowFloor.vue
  app/javascript/component_floors/rowRoom.vue
  app/javascript/component_floors/tableFloors.vue
  app/javascript/floor.vue
  app/javascript/packs/application.js
  app/javascript/store/modules/floor.js
  lib/tasks/default_data.rake
  package.json
  yarn.lock
Labels: LGTM
